export const TEST_DATA = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec gravida elit sed dui lobortis placerat. Nullam dui nisi, semper sit amet nisl nec, mattis ultrices nisi. Nunc ultricies augue a pulvinar lobortis. Etiam euismod vehicula purus, nec vehicula nunc faucibus eleifend. Proin dui libero, malesuada non ultricies vitae, ornare dictum purus. In efficitur nunc eu tempus elementum. Maecenas venenatis metus tincidunt lectus aliquet, a tristique enim fringilla. Duis ac turpis non enim pulvinar sagittis id non justo. Mauris sit amet pharetra purus.

Donec porttitor sollicitudin diam. Curabitur ante mi, mattis quis quam ut, pulvinar tristique justo. Ut at ultricies ex. Ut eget vulputate sapien. Sed rutrum enim et urna auctor, id luctus odio sagittis. Sed vel libero ac quam efficitur commodo vitae ac felis. Vestibulum turpis lectus, porttitor quis orci et, pellentesque convallis augue. Ut vitae feugiat metus. Mauris laoreet, dui vel aliquam lacinia, nisl turpis fringilla dui, in commodo ex tortor id lectus. Nam purus ligula, volutpat et rutrum nec, pretium et ante. Sed pellentesque venenatis eros non mollis. Nullam eu aliquet quam, a vestibulum ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Pellentesque purus nisi, sagittis id enim in, dictum egestas felis. Nulla porta, nunc non luctus hendrerit, tellus ligula congue eros, eu gravida purus nunc vulputate lorem. Pellentesque ultricies nisi vel blandit aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas nec ex at elit maximus sollicitudin quis sit amet nulla. Sed ut imperdiet ante. Proin varius leo quis convallis placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin efficitur justo vitae elit fermentum egestas. Maecenas mollis, turpis vel auctor hendrerit, est est sagittis metus, egestas tempor mauris dui a tellus. In nisl dui, lacinia vitae justo ut, commodo porttitor lacus. Nam purus tellus, euismod nec eros nec, tempus vehicula tellus. Proin placerat id diam eu ornare. Donec ac dictum enim.

Proin congue malesuada sem, sit amet aliquet ex tincidunt non. Curabitur at justo quis erat pretium lobortis sed eu lorem. Ut volutpat elit justo, quis consectetur tellus interdum sit amet. Etiam arcu tortor, egestas sit amet egestas a, sollicitudin vitae nibh. Vivamus ultrices est id ultricies mollis. Proin vitae iaculis lectus. Aliquam ultrices lacinia nisi, at feugiat sapien pellentesque eget. Aliquam eu suscipit quam. Ut vulputate purus id ante finibus, ut fermentum leo consectetur. Vivamus ultrices turpis nisi, bibendum ultricies mauris commodo eget. Suspendisse arcu orci, finibus vitae quam in, faucibus scelerisque odio.

Cras consequat elementum nunc. In venenatis tortor eu mauris semper finibus. Aliquam vehicula turpis vel euismod faucibus. Vivamus lobortis lectus ligula, sed viverra lorem hendrerit in. Ut rutrum dapibus ante, ac malesuada odio egestas nec. Curabitur eu lorem ac quam efficitur sagittis. Nullam non est in lectus hendrerit tempus quis eu eros. Praesent vel maximus ipsum. Etiam gravida dolor enim, sed venenatis tellus accumsan at. Suspendisse ipsum elit, suscipit ut ultrices a, imperdiet eu dolor.

Integer euismod, ex quis facilisis consequat, justo elit egestas tellus, sit amet imperdiet nulla eros vehicula dui. In quis molestie elit. Praesent rhoncus ante sit amet porta tempor. Pellentesque id euismod tortor. Suspendisse ornare leo vel lectus pharetra, eget pulvinar leo convallis. Nullam id pellentesque urna, non bibendum turpis. Ut diam felis, luctus at odio sollicitudin, venenatis dignissim tellus. Phasellus eget pharetra ex, ut fermentum massa. Sed laoreet magna non orci volutpat suscipit.

Suspendisse ut congue justo, ac volutpat lectus. Quisque feugiat augue lacinia, lacinia orci bibendum, eleifend nisl. Donec ultrices quam at enim convallis efficitur. Cras iaculis tortor in posuere dictum. Morbi finibus euismod nulla at feugiat. Maecenas placerat dolor eget malesuada blandit. Sed interdum cursus arcu, non laoreet turpis elementum et. Donec dignissim et nisl ut viverra. In hac habitasse platea dictumst. Maecenas eget turpis vitae enim cursus vehicula. Donec cursus tellus enim, quis ultricies ex convallis non. Nunc leo neque, rhoncus nec libero in, congue sodales augue. Nunc commodo quis odio porta elementum. Mauris vel rhoncus felis. Nulla facilisi. Fusce iaculis id massa id tincidunt.

Donec ac orci fermentum, imperdiet metus ut, varius lorem. Phasellus tincidunt dui nec elementum accumsan. Sed fringilla purus eget auctor venenatis. Pellentesque fermentum velit vitae libero efficitur placerat. Pellentesque facilisis urna at lectus faucibus, vitae pharetra libero pharetra. Pellentesque volutpat diam magna, eget finibus velit feugiat eu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus in scelerisque nisl.

Ut sit amet ipsum nec arcu rhoncus porta eget a nisi. Phasellus viverra, erat quis lacinia aliquam, tellus magna consectetur arcu, vitae ornare lectus felis imperdiet velit. Duis venenatis nulla quis rhoncus commodo. Proin fringilla tincidunt est, sit amet posuere magna. Phasellus nibh sem, porttitor non orci sed, consectetur vehicula nibh. Fusce turpis tortor, luctus in mi sit amet, luctus fringilla ligula. Pellentesque tellus elit, elementum feugiat fringilla non, accumsan eget lacus. In quis purus auctor lorem cursus tristique eu ac ipsum. Nullam quis metus eleifend, molestie mauris sed, malesuada nisi. Nam vel tincidunt odio. Morbi ante lectus, cursus sed dictum in, molestie sit amet leo. Quisque consequat gravida egestas.

Integer aliquet, erat in malesuada hendrerit, sapien tellus congue ipsum, eu lobortis elit augue quis augue. Sed hendrerit risus quis eleifend volutpat. Aenean tristique aliquet fringilla. Vivamus sed sollicitudin est. Cras congue, sem at mattis mattis, sem nibh auctor ligula, vel rhoncus nibh libero a ante. Aenean mauris nisi, euismod non libero ac, placerat blandit est. Maecenas eu metus accumsan, viverra odio et, placerat risus. Nulla vestibulum elit vel est convallis, volutpat laoreet sapien faucibus. Quisque auctor interdum efficitur. Morbi iaculis neque non rhoncus ultrices. In faucibus arcu scelerisque placerat bibendum. Vivamus posuere turpis tellus, et iaculis risus vulputate ut. Nulla facilisi.`;